const AUTH_LOGIN_API_CALL = 'AUTH_LOGIN_API_CALL';
const AUTH_SIGNUP_INITIALIZATION = 'AUTH_SIGNUP_INITIALIZATION';
const AUTH_SIGNUP_DATA_STORE = 'AUTH_SIGNUP_DATA_STORE';
const AUTH_OTP_RESEND = 'AUTH_OTP_RESEND';
const AUTH_OTP_REQUIRE = 'AUTH_OTP_REQUIRE';
const AUTH_OTP_VERIFY = 'AUTH_OTP_VERIFY';
const AUTH_FORGOT_PASSWORD_API_CALL = 'AUTH_FORGOT_PASSWORD_API_CALL';
const SET_USER_PROFILE_DATA_TO_STORE = 'SET_USER_PROFILE_DATA_TO_STORE';
const CURRENT_BALANCE_UPDATE = 'CURRENT_BALANCE_UPDATE';
const WINING_BALANCE_UPDATE = 'WINING_BALANCE_UPDATE';
const NAME_UPDATE_API_CALL = 'NAME_UPDATE_API_CALL';
const NAME_UPDATE = 'NAME_UPDATE';
const PASSWORD_UPDATE_API_CALL = 'PASSWORD_UPDATE_API_CALL';
const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
const LOGOUT_API_CALL = 'LOGOUT_API_CALL';
const DELETE_USER_INFO = 'DELETE_USER_INFO';
const USER_PROFILE_FETCH_API_CALL = 'USER_PROFILE_FETCH_API_CALL';
const DEVICE_TOKEN = 'DEVICE_TOKEN';

export {
  AUTH_LOGIN_API_CALL,
  AUTH_SIGNUP_INITIALIZATION,
  AUTH_SIGNUP_DATA_STORE,
  AUTH_OTP_RESEND,
  AUTH_OTP_REQUIRE,
  AUTH_OTP_VERIFY,
  AUTH_FORGOT_PASSWORD_API_CALL,
  SET_USER_PROFILE_DATA_TO_STORE,
  CURRENT_BALANCE_UPDATE,
  WINING_BALANCE_UPDATE,
  NAME_UPDATE_API_CALL,
  NAME_UPDATE,
  PASSWORD_UPDATE_API_CALL,
  PASSWORD_UPDATE,
  LOGOUT_API_CALL,
  DELETE_USER_INFO,
  USER_PROFILE_FETCH_API_CALL,
  DEVICE_TOKEN,
};
