const SET_WINNING_BALANCE = 'SET_WINNING_BALANCE';
const SET_CURRENT_BALANCE = 'SET_CURRENT_BALANCE';
const SET_WINNING_HISTORY = 'SET_WINNING_HISTORY';
const GET_TRANSATION_HISTORY_API_CALL = 'GET_TRANSATION_HISTORY_API_CALL';
const STORE_TRANSATION_HISTORY_TO_REDUCER =
  'STORE_TRANSATION_HISTORY_TO_REDUCER';
const TRANSTER_TO_CURRENT_BALANCE_API_CALL =
  'TRANSTER_TO_CURRENT_BALANCE_API_CALL';
const TRANSTER_TO_OTHER_ACCOUNT_API_CALL = 'TRANSTER_TO_OTHER_ACCOUNT_API_CALL';
const WINING_HISTORY_BY_USER_API_CALL = 'WINING_HISTORY_BY_USER_API_CALL';
const WINING_HISTORY_BY_USER_STORE = 'WINING_HISTORY_BY_USER_STORE';

export {
  SET_WINNING_BALANCE,
  SET_CURRENT_BALANCE,
  SET_WINNING_HISTORY,
  GET_TRANSATION_HISTORY_API_CALL,
  STORE_TRANSATION_HISTORY_TO_REDUCER,
  TRANSTER_TO_CURRENT_BALANCE_API_CALL,
  TRANSTER_TO_OTHER_ACCOUNT_API_CALL,
  WINING_HISTORY_BY_USER_API_CALL,
  WINING_HISTORY_BY_USER_STORE,
};
