const START_INIT_APP = 'START_INIT_APP';
const APP_INITIALIZATION = 'APP_INITIALIZATION';
const IS_SHOW_CART = 'IS_SHOW_CART';
const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
const COMMON_MODAL_DATA_SET = 'COMMON_MODAL_DATA_SET';
const LOADER_SHOW = 'LOADER_SHOW';
const LOADER_HIDE = 'LOADER_HIDE';
const PROFILE_MODAL_VISIBILITY = 'PROFILE_MODAL_VISIBILITY';
const UPDATE_IS_AUTHENTICATEED = 'UPDATE_IS_AUTHENTICATEED';
const INTERNET_CONNECTION_STATUS = 'INTERNET_CONNECTION_STATUS';
const SUGGESTION_API_CALL = 'SUGGESTION_API_CALL';
const SUGGESTION_STORE = 'SUGGESTION_STORE';
const RELOAD_APP = 'RELOAD_APP';
const NOTIFIED_NAV = 'NOTIFIED_NAV';
const NOTIFIED_SUB_NAV = 'NOTIFIED_SUB_NAV';
const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export {
  START_INIT_APP,
  APP_INITIALIZATION,
  IS_SHOW_CART,
  IS_AUTHENTICATED,
  COMMON_MODAL_DATA_SET,
  LOADER_SHOW,
  LOADER_HIDE,
  PROFILE_MODAL_VISIBILITY,
  UPDATE_IS_AUTHENTICATEED,
  INTERNET_CONNECTION_STATUS,
  SUGGESTION_API_CALL,
  SUGGESTION_STORE,
  RELOAD_APP,
  NOTIFIED_NAV,
  NOTIFIED_SUB_NAV,
  IMAGE_UPLOAD,
};
